### ISSUE TITLE
[BUG] Shopware v6.3.2.1 - Install for @shopware-pwa/cli@latest failed with code 1

### ISSUE THREAD

**Issue by lanluu** [vuestorefront/shopware-pwa#1202]
I followed the instruction given at https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/ for my current instance of Shopware v6.3.2.1 but always received the given error "Install for @shopware-pwa/cli@latest failed with code 1".

Surely, I successfully installed required Plugin for Shopware 6 given at https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/prepare-shopware.html.

I also tried to use the previous versions of CLI (4.x, 3.x) but the same error appeared always.

Any tip/help is appreciated.

Thanks and regards

**Comment by abvdveen** [comment]
@lanluu: had the same issue in a Hypernode docker container. Could be node version related. I had node version v10.21.0. After upgrading node to v15.0.1 error was gone. Not 100% certain if it was the node version that caused the error, as I also seemed to be missing yarn in that docker instance, which I installed when the error occurred. So make sure you have yarn installed, by checking yarn -v and then try npx @shopware-pwa/cli init

**Comment by lanluu** [comment]
@abvdveen thanks for your tip. i will try tonight! 😃

**Comment by lanluu** [comment]
I upgraded NodeJs and installed Yarn already.
Now, the clearer error appears:

node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/263412/lib/node_modules/@shopware-pwa/cli/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
**npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`**
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-25T15_23_26_663Z-debug.log
Install for [ '@shopware-pwa/cli@latest' ] failed with code 1

**Comment by lanluu** [comment]
Maybe it is the same as https://github.com/DivanteLtd/shopware-pwa/issues/748?

**Comment by rrrodzilla** [comment]
I got past this issue by downgrading node to version: 14.13.1

**Comment by patzick** [comment]
problem with Node 15 will be resolved with #1198
